# Generated by Django 6.0.4 on 2026-04-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('treatment', models.CharField(max_length=200)),
                ('total_amount', models.FloatField()),
                ('paid_amount', models.FloatField()),
                ('remaining_amount', models.FloatField()),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
