# Generated by Django 6.0.4 on 2026-04-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_created_at_patient_next_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='next_appointment',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone',
        ),
        migrations.AddField(
            model_name='patient',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='paid_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='remaining_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
