# Generated by Django 6.0.4 on 2026-04-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_next_appointment_remove_patient_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='patient',
            name='next_appointment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='paid_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='remaining_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='total_amount',
            field=models.FloatField(),
        ),
    ]
