# Generated by Django 6.0.4 on 2026-04-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_patient_is_paid_patient_next_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone',
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='paid_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='remaining_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
