# Generated by Django 6.0.4 on 2026-04-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_remove_patient_appointment_date_remove_patient_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
        migrations.AddField(
            model_name='patient',
            name='session_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('not_done', 'Not Done')], default='pending', max_length=20),
        ),
    ]
