# Generated by Django 6.0.4 on 2026-04-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_remove_patient_created_at_patient_session_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_manual_debt',
            field=models.BooleanField(default=False),
        ),
    ]
