# Generated by Django 6.0.4 on 2026-04-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patient_is_manual_debt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='remaining_amount',
        ),
    ]
