# Generated by Django 6.0.4 on 2026-05-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_remove_patient_remaining_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='show_today',
            field=models.BooleanField(default=False),
        ),
    ]
