# Generated by Django 6.0.4 on 2026-05-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_remove_patient_show_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='show_today',
            field=models.BooleanField(default=False),
        ),
    ]
