# Generated by Django 6.0.4 on 2026-05-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_patient_show_today'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='show_today',
        ),
    ]
