# Generated by Django 6.0.4 on 2026-05-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_remove_patient_show_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_appointment',
            field=models.BooleanField(default=False),
        ),
    ]
