# Generated by Django 6.0.4 on 2026-05-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_patient_is_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_today',
            field=models.BooleanField(default=False),
        ),
    ]
