# Generated by Django 6.0.4 on 2026-05-04 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_patient_is_today'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='is_today',
        ),
    ]
