# Generated by Django 6.0.4 on 2026-05-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_remove_patient_is_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_today',
            field=models.BooleanField(default=False),
        ),
    ]
