# Generated by Django 6.0.4 on 2026-05-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_patient_is_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='has_appointment',
            field=models.BooleanField(default=False),
        ),
    ]
