# Generated by Django 6.0.4 on 2026-05-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_patient_has_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='added_to_today',
            field=models.BooleanField(default=False),
        ),
    ]
